In [4]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
# create a column age_group
labels=['young Adult','Adult','Middle-aged','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  young Adult
2   50  Middle-aged
3   21  young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       senior
7   27  young Adult
8   26  young Adult
9   57  Middle-aged

In [14]:
# create column purchase_frequency_days
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [16]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [18]:
df=df.drop('promo_code_used',axis=1)

In [27]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [28]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp310-cp310-win_amd64.whl (17.7 MB)
     ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
      --------------------------------------- 0.2/17.7 MB 7.3 MB/s eta 0:00:03
     - -------------------------------------- 0.8/17.7 MB 9.6 MB/s eta 0:00:02
     -- ------------------------------------- 1.3/17.7 MB 10.3 MB/s eta 0:00:02
     ---- ----------------------------------- 1.8/17.7 MB 10.2 MB/s eta 0:00:02
     ---- ----------------------------------- 2.0/17.7 MB 9.6 MB/s eta 0:00:02
     ----- ---------------------------------- 2.6/17.7 MB 9.8 MB/s eta 0:00:02
     ------ --------------------------------- 3.1/17.7 MB 9.8 MB/s eta 0:00:02
     ------- -------------------------------- 3.5/17.7 MB 9.6 MB/s eta 0:00:02
     ------- -------------------------------- 3.5/17.7 MB 8.3 MB/s eta 0:00:02
     -------- ------------------------------- 3.7/17.7 MB 8.5 MB/s eta 0:00:02
     -------- ------------------------------- 3.9/17.7 MB 7.9 MB/s eta 0:00:02
     --------- ------------------------------ 4.1/17.7 MB 7.7 MB/s eta 0:00:02
     --------- ------------------------------ 4.3/17.7 MB 7.3 MB/s eta 0:00:02
     ---------- ----------------------------- 4.5/17.7 MB 7.1 MB/s eta 0:00:02
     ---------- ----------------------------- 4.7/17.7 MB 6.8 MB/s eta 0:00:02
     ---------- ----------------------------- 4.7/17.7 MB 6.6 MB/s eta 0:00:02
     ---------- ----------------------------- 4.7/17.7 MB 6.6 MB/s eta 0:00:02
     ---------- ----------------------------- 4.8/17.7 MB 5.8 MB/s eta 0:00:03
     ----------- ---------------------------- 4.9/17.7 MB 5.7 MB/s eta 0:00:03
     ----------- ---------------------------- 4.9/17.7 MB 5.7 MB/s eta 0:00:03
     ----------- ---------------------------- 4.9/17.7 MB 5.7 MB/s eta 0:00:03
     ----------- ---------------------------- 5.0/17.7 MB 4.9 MB/s eta 0:00:03
     ----------- ---------------------------- 5.0/17.7 MB 4.9 MB/s eta 0:00:03
     ----------- ---------------------------- 5.0/17.7 MB 4.5 MB/s eta 0:00:03
     ----------- ---------------------------- 5.1/17.7 MB 4.4 MB/s eta 0:00:03
     ----------- ---------------------------- 5.2/17.7 MB 4.4 MB/s eta 0:00:03
     ----------- ---------------------------- 5.2/17.7 MB 4.4 MB/s eta 0:00:03
     ----------- ---------------------------- 5.3/17.7 MB 4.1 MB/s eta 0:00:04
     ------------ --------------------------- 5.3/17.7 MB 4.0 MB/s eta 0:00:04
     ------------ --------------------------- 5.5/17.7 MB 3.9 MB/s eta 0:00:04
     ------------ --------------------------- 5.6/17.7 MB 3.9 MB/s eta 0:00:04
     ------------- -------------------------- 5.8/17.7 MB 3.9 MB/s eta 0:00:04
     ------------- -------------------------- 5.9/17.7 MB 3.8 MB/s eta 0:00:04
     ------------- -------------------------- 6.1/17.7 MB 3.8 MB/s eta 0:00:04
     -------------- ------------------------- 6.3/17.7 MB 3.9 MB/s eta 0:00:03
     -------------- ------------------------- 6.5/17.7 MB 3.9 MB/s eta 0:00:03
     -------------- ------------------------- 6.6/17.7 MB 3.9 MB/s eta 0:00:03
     -------------- ------------------------- 6.6/17.7 MB 3.9 MB/s eta 0:00:03
     --------------- ------------------------ 6.7/17.7 MB 3.7 MB/s eta 0:00:03
     --------------- ------------------------ 6.9/17.7 MB 3.7 MB/s eta 0:00:03
     ---------------- ----------------------- 7.1/17.7 MB 3.7 MB/s eta 0:00:03
     ---------------- ----------------------- 7.3/17.7 MB 3.8 MB/s eta 0:00:03
     ----------------- ---------------------- 7.5/17.7 MB 3.8 MB/s eta 0:00:03
     ----------------- ---------------------- 7.8/17.7 MB 3.8 MB/s eta 0:00:03
     ------------------ --------------------- 8.0/17.7 MB 3.8 MB/s eta 0:00:03
     ------------------ --------------------- 8.2/17.7 MB 3.9 MB/s eta 0:00:03
     ------------------- -------------------- 8.5/17.7 MB 3.9 MB/s eta 0:00:03
     ------------------- -------------------- 8.8/17.7 MB 4.0 MB/s eta 0:00:03
     -------------------- ------------------- 9.0/17.7 MB 4.0 MB/s eta 0:00:03
     -------------------- ------------------- 9.2/17.7 MB 4.0 MB/s eta 0:00:03
     --------------------- ------------------ 9.5/17.7 MB 4.0 MB/s eta 0:00:03
     --------------------- ------------------ 9.7/17.7 MB 4.0 MB/s eta 0:00:02
     ---------------------- ----------------- 9.8/17.7 MB 4.0 MB/s eta 0:00:02
     ---------------------- ----------------- 10.0/17.7 MB 4.0 MB/s eta 0:00:02
     ----------------------- ---------------- 10.4/17.7 MB 4.0 MB/s eta 0:00:02
     ----------------------- ---------------- 10.6/17.7 MB 4.0 MB/s eta 0:00:02
     ------------------------ --------------- 10.8/17.7 MB 4.0 MB/s eta 0:00:02
     ------------------------ --------------- 11.0/17.7 MB 3.9 MB/s eta 0:00:02
     ------------------------- -------------- 11.3/17.7 MB 3.9 MB/s eta 0:00:02
     -------------------------- ------------- 11.6/17.7 MB 3.9 MB/s eta 0:00:02
     -------------------------- ------------- 11.8/17.7 MB 3.8 MB/s eta 0:00:02
     --------------------------- ------------ 12.0/17.7 MB 3.8 MB/s eta 0:00:02
     --------------------------- ------------ 12.1/17.7 MB 3.7 MB/s eta 0:00:02
     --------------------------- ------------ 12.3/17.7 MB 3.7 MB/s eta 0:00:02
     ---------------------------- ----------- 12.5/17.7 MB 3.7 MB/s eta 0:00:02
     ---------------------------- ----------- 12.7/17.7 MB 3.6 MB/s eta 0:00:02
     ----------------------------- ---------- 13.0/17.7 MB 3.6 MB/s eta 0:00:02
     ----------------------------- ---------- 13.2/17.7 MB 3.6 MB/s eta 0:00:02
     ------------------------------ --------- 13.3/17.7 MB 3.6 MB/s eta 0:00:02
     ------------------------------ --------- 13.4/17.7 MB 3.5 MB/s eta 0:00:02
     ------------------------------ --------- 13.5/17.7 MB 3.4 MB/s eta 0:00:02
     ------------------------------ --------- 13.6/17.7 MB 3.4 MB/s eta 0:00:02
     ------------------------------ --------- 13.7/17.7 MB 3.3 MB/s eta 0:00:02
     ------------------------------- -------- 13.7/17.7 MB 3.3 MB/s eta 0:00:02
     ------------------------------- -------- 13.8/17.7 MB 3.3 MB/s eta 0:00:02
     ------------------------------- -------- 13.9/17.7 MB 3.3 MB/s eta 0:00:02
     ------------------------------- -------- 14.0/17.7 MB 3.2 MB/s eta 0:00:02
     ------------------------------- -------- 14.0/17.7 MB 3.2 MB/s eta 0:00:02
     ------------------------------- -------- 14.1/17.7 MB 3.2 MB/s eta 0:00:02
     ------------------------------- -------- 14.1/17.7 MB 3.2 MB/s eta 0:00:02
     -------------------------------- ------- 14.2/17.7 MB 3.1 MB/s eta 0:00:02
     -------------------------------- ------- 14.3/17.7 MB 3.1 MB/s eta 0:00:02
     -------------------------------- ------- 14.3/17.7 MB 3.1 MB/s eta 0:00:02
     -------------------------------- ------- 14.4/17.7 MB 3.0 MB/s eta 0:00:02
     -------------------------------- ------- 14.4/17.7 MB 3.0 MB/s eta 0:00:02
     -------------------------------- ------- 14.5/17.7 MB 3.0 MB/s eta 0:00:02
     --------------------------------- ------ 14.6/17.7 MB 3.0 MB/s eta 0:00:02
     --------------------------------- ------ 14.7/17.7 MB 2.9 MB/s eta 0:00:02
     --------------------------------- ------ 14.8/17.7 MB 2.9 MB/s eta 0:00:01
     --------------------------------- ------ 14.9/17.7 MB 2.9 MB/s eta 0:00:01
     --------------------------------- ------ 15.0/17.7 MB 3.0 MB/s eta 0:00:01
     ---------------------------------- ----- 15.1/17.7 MB 3.1 MB/s eta 0:00:01
     ---------------------------------- ----- 15.2/17.7 MB 3.2 MB/s eta 0:00:01
     ---------------------------------- ----- 15.4/17.7 MB 3.2 MB/s eta 0:00:01
     ----------------------------------- ---- 15.5/17.7 MB 3.3 MB/s eta 0:00:01
     ----------------------------------- ---- 15.6/17.7 MB 3.3 MB/s eta 0:00:01
     ----------------------------------- ---- 15.8/17.7 MB 3.3 MB/s eta 0:00:01
     ------------------------------------ --- 15.9/17.7 MB 3.3 MB/s eta 0:00:01
     ------------------------------------ --- 16.0/17.7 MB 3.3 MB/s eta 0:00:01
     ------------------------------------ --- 16.2/17.7 MB 3.3 MB/s eta 0:00:01
     ------------------------------------- -- 16.4/17.7 MB 3.3 MB/s eta 0:00:01
     ------------------------------------- -- 16.6/17.7 MB 3.3 MB/s eta 0:00:01
     ------------------------------------- -- 16.8/17.7 MB 3.3 MB/s eta 0:00:01
     -------------------------------------- - 16.9/17.7 MB 3.4 MB/s eta 0:00:01
     -------------------------------------- - 17.1/17.7 MB 3.4 MB/s eta 0:00:01
     ---------------------------------------  17.3/17.7 MB 3.4 MB/s eta 0:00:01
     ---------------------------------------  17.5/17.7 MB 3.3 MB/s eta 0:00:01
     ---------------------------------------  17.7/17.7 MB 3.4 MB/s eta 0:00:01
     ---------------------------------------  17.7/17.7 MB 3.4 MB/s eta 0:00:01
     ---------------------------------------- 17.7/17.7 MB 3.3 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="nithish",
    database="shopping_db"
)

cursor = conn.cursor()

In [31]:
!pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.52-cp310-cp310-win_amd64.whl (2.2 MB)
     ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
     --- ------------------------------------ 0.2/2.2 MB 4.1 MB/s eta 0:00:01
     ------------ --------------------------- 0.7/2.2 MB 8.3 MB/s eta 0:00:01
     --------------------- ------------------ 1.2/2.2 MB 9.2 MB/s eta 0:00:01
     ---------------------------- ----------- 1.6/2.2 MB 9.0 MB/s eta 0:00:01
     ------------------------------------ --- 1.9/2.2 MB 8.9 MB/s eta 0:00:01
     ------------------------------------- -- 2.0/2.2 MB 8.6 MB/s eta 0:00:01
     ---------------------------------------- 2.2/2.2 MB 6.9 MB/s eta 0:00:00
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
     ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
     ---------------------------------------- 45.7/45.7 kB 1.1 MB/s eta 0:00:00
Collecting greenlet>=1
  Downloading greenlet-3.5.5-cp310-cp310-win_amd64.whl (322 kB)
     ---------------------------------------- 0.0/322.8 kB ? eta -:--:--
     ---------------------------- --------- 245.8/322.8 kB 7.6 MB/s eta 0:00:01
     -------------------------------------- 322.8/322.8 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.16.0)
Installing collected packages: pymysql, greenlet, sqlalchemy
Successfully installed greenlet-3.5.5 pymysql-1.2.0 sqlalchemy-2.0.52

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    "mysql+pymysql://root:nithish@localhost/shopping_db"
)

In [19]:
df.to_sql(
    'shopping_data',
    con=engine,
    if_exists='replace',
    index=False
)

3900

In [20]:
print(df.shape)

(3900, 19)

In [21]:
print(df.head())

   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly  Middle-aged                       14
1            Fortnightly  young Adult                       14
2                 Weekly  Middle-aged                        7
3                 Weekly  young Adult                        7
4               Annually  Middle-aged                      365

In [22]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:YOUR_MYSQL_PASSWORD@localhost/shopping_db"
)

print(engine.connect())

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [23]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:nithish@localhost/shopping_db"
)

In [24]:
print(engine.connect())

<sqlalchemy.engine.base.Connection object at 0x000001E3FE2BEA40>

In [25]:
with engine.connect() as connection:
    print("MySQL connection successful!")

MySQL connection successful!

In [26]:
df.to_sql(
    'shopping_data',
    con=engine,
    if_exists='replace',
    index=False
)

3900